/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols_overlays.toml (Final Fantasy 7)
 *
 * Overlay symbols are SCOPED. Most FF7 overlays share a load address
 * (battle/brom/dschange/ending/field/world at 0x800A0000; the menus at
 * 0x801D0000; batini/barrier/lv5deth at 0x801B0000), so one address means
 * different things depending on what is resident. There is deliberately no
 * bare func_<pc> alias here — it could not be unambiguous.
 *
 * These addresses are NOT in the static generated/ tree, which covers the
 * main executable only. They belong to code reached through the overlay
 * cache (psxrecomp/docs/COMPILING_OVERLAYS.md).
 */
#pragma once

#define PSX_OVL_BATTLE_BASE 0x800A0000u
#define PSX_OVL_BROM_BASE 0x800A0000u
#define PSX_OVL_DSCHANGE_BASE 0x800A0000u
#define PSX_OVL_ENDING_BASE 0x800A0000u
#define PSX_OVL_FIELD_BASE 0x800A0000u
#define PSX_OVL_WORLD_BASE 0x800A0000u
#define PSX_OVL_BARRIER_BASE 0x801B0000u
#define PSX_OVL_BATINI_BASE 0x801B0000u
#define PSX_OVL_LV5DETH_BASE 0x801B0000u
#define PSX_OVL_BGINMENU_BASE 0x801D0000u
#define PSX_OVL_CNFGMENU_BASE 0x801D0000u
#define PSX_OVL_ITEMMENU_BASE 0x801D0000u
#define PSX_OVL_SAVEMENU_BASE 0x801D0000u

/* ---- batini ---- */
/* contextual: ff7-decomp 24a46a990dcc (batini) */
#define PSX_FN_BATINI_g_BattleState 0x800F83ACu

/* ---- battle ---- */
/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_StatusBitTable 0x800A04D0u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ClearStatusBit 0x800A6CC0u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ExpireDeathSentence 0x800A6D10u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_TickPoison 0x800A6D88u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ResolveMagicActionIndex 0x800A73C0u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ResolveSummonActionIndex 0x800A73D8u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ResolveEnemySkillActionIndex 0x800A76ACu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ResolveLimitActionIndex 0x800A778Cu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ResolveCaitSithSlotsResult 0x800A9C24u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_IsDamageNullified 0x800ACE14u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_QueueUnassignedResultDisplay 0x800AD088u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ApplyDefaultAbsorbEffect 0x800AD420u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ApplySadnessReduction 0x800AD890u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ApplyKillCountBonus 0x800AE318u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_TryApplyHitEffect 0x800AF1D4u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ClearActorSlotReferences 0x800AF594u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_ApplyConditionalReduction 0x800B0E5Cu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_InvalidateQueuedMessages 0x800B1304u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleEffectRegister 0x800BBEACu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_EnqueueLoadImage 0x800D2538u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BATTLE_FlushImageQueue 0x800D25E8u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleGetPartPosition 0x800D3994u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleEventQueuePush 0x800D4FA8u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleFixedPointRampUpdate 0x800D5230u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleAnimationUpdate 0x800D5350u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleEntityGetCenter 0x800D54ECu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_BattleCommandSend 0x800D55F4u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_StatusExpireTable 0x800E7AB4u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_AtbBarPulseColor 0x800F32C4u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_AtbBarPulseValue 0x800F32C6u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_ActiveCharsHPMPInited 0x800F32C8u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_CombatantTurnState 0x800F5BB8u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_dbIndex 0x800F8368u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_BattleState 0x800F83ACu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_db 0x800FAFF4u

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_modelScreenPos 0x801516FCu

/* contextual: ff7-decomp 24a46a990dcc (battle) */
#define PSX_FN_BATTLE_g_cDb 0x801517C0u

/* ---- field ---- */
/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldLoadMimDatFiles 0x800A1368u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_StopFieldMapPreload 0x800A1498u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PreloadNextFieldMap 0x800A14D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldMain 0x800A16CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldMainLoop 0x800A2314u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldLoadMimToVram 0x800A2D5Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldButtonsUpdate 0x800A2F78u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBackgroundInitPackets 0x800A3020u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_AddBackgroundToRender 0x800A364Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldCalcLinearStep 0x800A4094u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldCalcEaseInOut 0x800A4134u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldCalcWorldToScreenPos 0x800A41CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGShakeUpdate 0x800A424Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGScrollInit 0x800A4430u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldCalcPointOnLine 0x800A45D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGClampPos 0x800A47F8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGGetEntityScreenPos 0x800A48B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGScrollUpdate 0x800A496Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBGUpdateDrawenv 0x800A4BECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityInitPos 0x800A5FB4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityAddRotate 0x800A635Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityAnimationUpdate 0x800A6418u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityMovementUpdate 0x800A65A4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityGatewayMapLoad 0x800A82A0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityCheckTalk 0x800A8304u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityGetDirVectorX 0x800A8600u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityGetDirVectorY 0x800A8620u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityDirByVec 0x800A8640u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityAutoMove 0x800A8858u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityWalkmechCross 0x800A8968u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityVectorSub 0x800A8DF4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityCalculateZ 0x800A8E34u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityMove 0x800A8F88u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityCollisionCheck 0x800A9B64u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntitySqrDistToLine 0x800A9CE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityLineCheck 0x800A9EECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityLineInteract 0x800AA180u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityLineClear 0x800AA32Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityGatewayCheck 0x800AA348u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityBgTriggerActivate 0x800AA514u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityTriggerCheck 0x800AA5E4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityBgTriggerInit 0x800AA870u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelLoadAndInit 0x800AA930u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_HandleKawaiDataInModel 0x800AAB24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DebugRunEveryLoop 0x800AB2ACu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldCameraAssign 0x800AB2B4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldUpdateMovieStream 0x800AB310u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldRainInit 0x800AB4ACu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldRainAddToRender 0x800AB5E8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldRainUpdate 0x800AB728u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldGetRandomU8FromList 0x800AB9C8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldGetNextRandomU8 0x800ABA34u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldBattleCheck 0x800ABA70u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldArrowsInit 0x800ABF0Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldArrowsAddToRender 0x800ABFE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_LoadLocalFieldModelAndInitAll 0x800AC35Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelCreatePktsAndScale 0x800ACBA0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelCreatePktsForPart 0x800ACC5Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelLoadBsxTexToVram 0x800AD7B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelBsxTdbModify 0x800AD858u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelStructInit 0x800ADAA4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelLoadGlobalModels 0x800ADC90u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelLoadBcx 0x800ADD70u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelPrepareRender 0x800AE23Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelAddToRender 0x800AE4DCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelAnimCalcMtrxs 0x800AEE24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelScaleModel 0x800AF6ECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelScalePartVrtxs 0x800AF96Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldModelScaleAnimTranslat 0x800AFAC4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiClearData 0x800AFDE4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiExecute 0x800AFE1Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetCustomLightToModelPkts 0x800B0618u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetVertexColorFromLighting 0x800B0A48u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetColorToModelPkts 0x800B0EDCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetColorToPartPkts 0x800B0FB0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiLoadEyesMouthTexToVram 0x800B1C7Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiLightingApplyToModel 0x800B1E40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiLightingApplyToPolyColor 0x800B2598u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetModelTransparency 0x800B2A00u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetColorToPktsBelowLvl 0x800B2DD4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetColorToPartPktsBelowLvl 0x800B2F40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiFadeModelColor 0x800B480Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetCustomLighting 0x800B4B04u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiColorFadeBelowLvl 0x800B4EACu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetLightingToModelPkts 0x800B5260u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetLightingToPartPkts 0x800B5504u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetSplashToPktsBelowLvl 0x800B62C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiInitSplashPkts 0x800B69C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiSetPartAttribute 0x800B6AE4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiApplyBoneTransform 0x800B6B4Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiRenderClippedPart 0x800B79B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiDirectionalColorGradient 0x800B86D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiGradientColor 0x800B8CF0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_KawaiAnimatedPointLight 0x800B9B0Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventInit 0x800BA534u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventUpdate 0x800BA65Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldInitDefaultValues 0x800BA7C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventRunInit 0x800BAF54u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEnablePartyModels 0x800BB1B4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventOpcodeCycle 0x800BB3A8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldUpdateAnimationState 0x800BBBCCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventRequestRun 0x800BBF74u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_ResetFieldRenderState 0x800BC338u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_UpdateFieldExitArrows 0x800BC438u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DrawFieldExitArrow 0x800BC4D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DebugUpdateActor 0x800BC9FCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DebugPrintOpcode 0x800BEAD4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugAddParseValueToPage2 0x800BECA4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventReadMemoryU8 0x800BEE10u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventWriteMemoryU8 0x800BF3ACu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventReadMemoryS16 0x800BF908u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventWriteMemoryS16 0x800C0248u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBad 0x800C0B54u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWait1 0x800C0BE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWait 0x800C0C18u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSet 0x800C0DE0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSet2 0x800C0E5Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLbyte 0x800C0EDCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncHbyte 0x800C0F58u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFunc2byte 0x800C0FD8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSetx 0x800C107Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGetx 0x800C1214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSrchx 0x800C13B0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBiton 0x800C1674u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBitof 0x800C1714u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBitxr 0x800C17B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLine 0x800C1858u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSline 0x800C1AB4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLinon 0x800C1BF4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSlip 0x800C1D24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncIf 0x800C1DE4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLif 0x800C1EECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_IfCheck 0x800C2000u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncIf2 0x800C228Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLif2 0x800C2394u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_If2CheckSigned 0x800C24A8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncIf2u 0x800C2754u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLif2u 0x800C285Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_If2CheckUnsigned 0x800C2970u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncKeyEx 0x800C2BFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncKeyon 0x800C2CA8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncKeyof 0x800C2D54u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncReq 0x800C2F7Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncReqsw 0x800C2FFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncReqew 0x800C307Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPreq 0x800C30FCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrqsw 0x800C31E4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrqew 0x800C32CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventRequest 0x800C33B4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRet 0x800C3A20u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRetto 0x800C3C34u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBack 0x800C3EA0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLback 0x800C3F1Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSkip 0x800C3FA0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLskip 0x800C401Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMjump 0x800C40A4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPmjmp 0x800C42B0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPmjmp2 0x800C4350u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMgame 0x800C43C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBatle 0x800C45ACu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventClearAkaoStruct 0x800C46A4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAkao 0x800C46D0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAkao2 0x800C4804u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSe 0x800C493Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMusic 0x800C49ECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMusvt 0x800C4A40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMusvm 0x800C4A94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCmusc 0x800C4AE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SetAndApplyAkao 0x800C4BCCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_GetAkaoBlockOffset 0x800C4C9Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBmusc 0x800C4CE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncFmusc 0x800C4DE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTutor 0x800C4EE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMulck 0x800C506Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgmovie 0x800C50ECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrlo 0x800C5194u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDskcg 0x800C523Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncUc 0x800C532Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBtlon 0x800C5414u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpdsp 0x800C54BCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMvcam 0x800C5564u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGmovr 0x800C560Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCc 0x800C5668u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncChar 0x800C5740u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDfanm 0x800C5898u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCcanm 0x800C5A2Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_StartModelAnimation 0x800C5B38u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnime 0x800C5CE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnimEx 0x800C5E80u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCanim 0x800C5FF4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCanmEx 0x800C63CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnimw 0x800C6748u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnimb 0x800C684Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMove 0x800C6924u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncFmove 0x800C6D64u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCmove 0x800C6FD8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncFcfix 0x800C728Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncJump 0x800C7354u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLader 0x800C75F0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPmova 0x800C7C3Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMova 0x800C7CE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldMoveToEntityUpdate 0x800C7D5Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDira 0x800C814Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPdira 0x800C81C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSetDirByActorId 0x800C826Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTura 0x800C8514u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPtura 0x800C8588u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEntityTurnToEntity 0x800C8634u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncOfstd 0x800C8B98u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncOfstw 0x800C8F64u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTurnw 0x800C9080u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTurn 0x800C91D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTurnr 0x800C955Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDir 0x800C9A20u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSlidr 0x800C9B88u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSldr2 0x800C9C84u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTalkr 0x800C9D80u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTlkr2 0x800C9E7Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMsped 0x800C9F78u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAsped 0x800CA074u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGtdir 0x800CA158u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPgtdr 0x800CA254u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGetai 0x800CA394u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGetaxy 0x800CA490u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAxyzi 0x800CA5D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPxyzi 0x800CA77Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncVisi 0x800CA95Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncTlkon 0x800CAA24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncXyzi 0x800CAAECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncXyz 0x800CAC98u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncXyi 0x800CADFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMes 0x800CAF60u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpnam 0x800CB01Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAsk 0x800CB0B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWclsEx 0x800CB1CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWsizw 0x800CB28Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWsize 0x800CB354u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWrow 0x800CB450u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWmove 0x800CB4F8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWrest 0x800CB5C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWclse 0x800CB660u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWmode 0x800CB718u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnd 0x800CB7C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAnd2 0x800CB858u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncOr 0x800CB8F4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncOr2 0x800CB98Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncXor 0x800CBA28u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncXor2 0x800CBAC0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPlus 0x800CBB5Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPlusEx 0x800CBBF4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPlus2 0x800CBCA4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPls2Ex 0x800CBD40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMinus 0x800CBDFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMinsEx 0x800CBE94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMins2 0x800CBF40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMns2Ex 0x800CBFDCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMul 0x800CC098u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMul2 0x800CC134u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDiv 0x800CC1D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDiv2 0x800CC284u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRemai 0x800CC358u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRema2 0x800CC404u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncInc 0x800CC4D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncIncEx 0x800CC558u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncInc2 0x800CC5ECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncInc2Ex 0x800CC670u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDec 0x800CC70Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDecEx 0x800CC78Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDec2 0x800CC824u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDec2Ex 0x800CC8A8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRandm 0x800CC944u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRdmsd 0x800CC9ECu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgon 0x800CCA68u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgoff 0x800CCB10u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgclr 0x800CCBBCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgrol 0x800CCC3Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgrol2 0x800CCCC8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPmvie 0x800CCD54u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMovie 0x800CCE94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMvief 0x800CCFE8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpjpo 0x800CD0C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScr2d 0x800CD16Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrlc 0x800CD214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrla 0x800CD2E8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrlp 0x800CD3F0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrcc 0x800CD554u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScr2dc 0x800CD5F0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScr2dl 0x800CD6B0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncScrlw 0x800CD770u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncStpal 0x800CD834u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncStpls 0x800CD91Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLdpal 0x800CDA24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLdpls 0x800CDB0Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventRectClear 0x800CDC14u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCppal 0x800CDC28u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCppal2 0x800CDD40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRtpal 0x800CDE8Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncRtpal2 0x800CE054u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAdpal 0x800CE214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncAdpal2 0x800CE480u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMppal2 0x800CE6F4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMppal 0x800CE904u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SetPcModel 0x800CEB20u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPc 0x800CEB94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrtyp 0x800CEE44u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrtym 0x800CF028u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrtye 0x800CF140u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSptye 0x800CF200u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGptye 0x800CF2BCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyReplace 0x800CF368u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyCompare 0x800CF4CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyFromBank2ToSave 0x800CF5A0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyFromSaveToBank2 0x800CF60Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyRemove 0x800CF66Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PartyAdd 0x800CF6C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncPrtyq 0x800CF718u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMembq 0x800CF874u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMmbPlusMinus 0x800CF9B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMmblk 0x800CFAF0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMmbuk 0x800CFB84u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSolid 0x800CFC1Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncVwoft 0x800CFCE4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncJoin 0x800CFE78u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSplit 0x800D0180u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventJoinSet 0x800D0518u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSplitSet 0x800D0938u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSplitJoinSetMove 0x800D0B4Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSplitJoinEndMove 0x800D1200u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSplitJoinSetTurn 0x800D1350u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventSplitJoinEndTurn 0x800D152Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncFade 0x800D1654u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncNfade 0x800D184Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncFadew 0x800D195Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncIdlck 0x800D1A80u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGwcol 0x800D1B94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSwcol 0x800D1C68u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncLstmp 0x800D1D3Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncShake 0x800D1DB8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncStitm 0x800D1F20u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDlitm 0x800D1FDCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCkitm 0x800D2098u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSpcal 0x800D2164u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgscr 0x800D2794u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBgdph 0x800D28A8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSmtra 0x800D298Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncDmtra 0x800D2A70u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCmtra 0x800D2B60u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMenu 0x800D2C60u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMenu2 0x800D2E94u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGetpc 0x800D2F3Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpara 0x800D3004u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpra2 0x800D3124u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSin 0x800D3264u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncCos 0x800D3330u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SystemRefreshParty 0x800D33FCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SystemResoreParty 0x800D348Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMhmmx 0x800D3548u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncHmpmx 0x800D368Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpPlus 0x800D3728u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncMpMinus 0x800D3840u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncHpPlus 0x800D3958u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncHpMinus 0x800D3A70u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGoldPlus 0x800D3B88u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncGoldMinus 0x800D3C18u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncChgld 0x800D3CA8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncChmph 0x800D3D40u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncChmst 0x800D3DCCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncSttim 0x800D3E64u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWspcl 0x800D3F30u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncWnumb 0x800D4038u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBtlmd 0x800D4160u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBtmd2 0x800D4214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBtrlt 0x800D4300u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBtltb 0x800D4378u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncBlink 0x800D4420u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncKawai 0x800D44E8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_OpcodeFuncKawiw 0x800D4780u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DebugDummyFunc 0x800D4838u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DebugPrintToFieldWindow 0x800D4840u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldEventDebugError 0x800D4848u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldWindowResetAll 0x800D48C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldWindowReset 0x800D493Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldWindowSetStateToClose 0x800D4B28u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogSetWindowStyleCbc 0x800D4BC0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldWindowResetTextAll 0x800D4BFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogSetSize 0x800D4C68u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogMove 0x800D4E24u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogSetWindowHeight 0x800D4E88u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogMessageUpdateStates 0x800D4EB4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogAskUpdateStates 0x800D5228u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_PlayWindowPointerClickSound 0x800D5750u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogWindowInit 0x800D579Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogWindowGrowth 0x800D5A60u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogCopyTextFromField 0x800D5C9Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DialogScrollText 0x800D6D44u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_DialogScrollTextDuringOk 0x800D6E0Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogWindowInitNext 0x800D6F6Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogWindowDecrease 0x800D707Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDialogGetVariableFromBank 0x800D726Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_ConvertDigitToString 0x800D775Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_ConvertNumToStrWithSpace 0x800D785Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_ConvertHexToString 0x800D7970u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_CopyDialogToMapName 0x800D7A58u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SystemMessageSetCharName 0x800D7C98u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugInitBuffers 0x800D7D6Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPagesResetPosSize 0x800D8194u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageInit 0x800D828Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageSetPosSize 0x800D8334u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageAddPos 0x800D83A8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageAddSize 0x800D8420u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageIsRender 0x800D8498u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageResetStrings 0x800D84CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugRenderClear 0x800D85C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugRender 0x800D85FCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugRenderPage 0x800D8710u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugRenderString 0x800D9C04u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_AddStrNextDebugRow 0x800D9F00u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_AddColorStrNextDebugRow 0x800D9FFCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SetStrToDebugRow 0x800DA124u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SetDebugStrRowColor 0x800DA194u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageSetHeadRow 0x800DA1D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageSetColor 0x800DA214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageNotInit 0x800DA28Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugPageHide 0x800DA2CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugTranspSwitch 0x800DA310u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringCopy 0x800DA334u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringConcat 0x800DA368u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringSize 0x800DA3C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringPartCopy 0x800DA3F0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringU8hex 0x800DA424u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringU16hex 0x800DA444u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugStringU32hex 0x800DA480u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_FieldDebugIntToString 0x800DA4FCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldFileInfo 0x800DA5B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldLzsInfo 0x800DA5C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldFileTable 0x800DA5C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WmPreSector 0x800DEF80u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WmPreSize 0x800DEF84u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugDigits 0x800E0208u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldOpcodes 0x800E0228u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_RandomTable 0x800E0638u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_DialogDigitCharacters 0x800E0738u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugRb 0x800E1024u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugRChars 0x800E41B8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugRRect 0x800E41BCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugRLines 0x800E41C0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugRDm 0x800E41C4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldDebugTransp 0x800E4210u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowReplaceBank 0x800E4214u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowStringPtr 0x800E4234u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowTotalRowsHeight 0x800E424Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_DebugText 0x800E4254u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowNameCopyCount 0x800E4278u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowReplaceParam 0x800E4280u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_DebugMessageBuffer 0x800E4288u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldRain 0x800E42D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_RainForce 0x800E48D8u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_EntityForSplitJoin 0x800E48F0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowString 0x800E4944u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldMoviePlayed 0x800E4D44u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowReplaceBankAddr 0x800E4D48u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_FieldRenderData 0x800E4DF0u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowExtraRows 0x801142CCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_SavedScriptIds 0x801142D4u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowWaitTime 0x8011445Cu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowTextBudget 0x80114470u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowFastForwardLevel 0x80114480u

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowBuffer 0x801144DCu

/* contextual: ff7-decomp 24a46a990dcc (field) */
#define PSX_FN_FIELD_g_WindowBufferPos 0x8011451Cu

/* ---- itemmenu ---- */
/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_SwapS32 0x801D03B4u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_Quicksort 0x801D03C8u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_SwapU16 0x801D0618u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_Sign 0x801D062Cu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByType 0x801D0650u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByMost 0x801D069Cu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByLeast 0x801D0704u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByName 0x801D076Cu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByField 0x801D081Cu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByBattle 0x801D08E4u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_CompareItemsByThrow 0x801D09ACu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_SwapItemSlots 0x801D0A74u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_ArrangeItems 0x801D0AACu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_EvictWeakestStolenMateria 0x801D2974u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_GetLowestStealPriority 0x801D29C4u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_OfferMateriaToSteal 0x801D2A18u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_ReequipReturnedMateria 0x801D2ABCu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_RemoveMateriaFromPlayer 0x801D2C00u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_FinalizeMateriaSteal 0x801D2CDCu

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_StealAllMateria 0x801D2D74u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_ReturnStolenMateria 0x801D2E84u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_UnequipCharacterMateria 0x801D2F00u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_BackupCharacterMateria 0x801D3018u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_RestoreCharacterMateria 0x801D3138u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_g_MateriaPriority 0x801D3834u

/* contextual: ff7-decomp 24a46a990dcc (itemmenu) */
#define PSX_FN_ITEMMENU_g_MateriaStealLoot 0x801D3F60u

/* ---- savemenu ---- */
/* contextual: ff7-decomp 24a46a990dcc (savemenu) */
#define PSX_FN_SAVEMENU_g_MenuStartMode 0x801E2CF8u

/* contextual: ff7-decomp 24a46a990dcc (savemenu) */
#define PSX_FN_SAVEMENU_menus 0x801E379Cu
