/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Final Fantasy 7)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800110C0u
#define func_800110C0 BootEntry  /* alias */
